name: Commms Weekly Call Reminder
on:
  schedule:
    - cron:  '0 15 * * 2'
  workflow_dispatch:
jobs:
  send-updates:
    name: Sends alerts to the comms channel
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2     
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        run: pip install -r requirements.txt

      - name: Send alerts to Discord
        env:
          IMG: ./resources/Banner_comms.png
          TITLE: Comms Working Group Call
          TEXT: 'Hi everyone 😁☀️🌈\n☎️ Comms Working Group call in 50min on Working Group VC - Comms channel https:\/\/discord.gg\/s2JuQCBNS4\nAGENDA & CALL NOTES\nhttps:\/\/docs.google.com\/document\/d\/1UTNNyYLf6WC1wlytoU9IJ46z2I32NX0MrtJOs3j9Ahw\/edit\n**MANIFESTO**\nhttps:\/\/docs.google.com\/document\/d\/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI\/edit#\n**MIRO BOARD**\nLink: https:\/\/miro.com\/app\/board\/o9J_kjDw5AE=\/\nPassword: TokenEngineering' 
          KEY: ${{ secrets.EncryptionKey }}
          URL: 'af83a8467d7b62352a720d02bb8871050b44c1081e379a8663201b4f4ac7a1aa96591b513bb830bd25f41cb51f3d7dc52553df31d242d7abd9ee144aec2d81ddf40f48a37372ffbbea7045f18957cdb932ccf8f8bb1ef7cc336d7cf91959ee56ff39559522977211ee5997c66f245ce12564106d64ab2d581a4de41373655a2cb8350c8fce87eff9017d50f537d6e5fc85f9278434947f88bf1a695e30a58433'
        run: python actions/alerts.py
        
