name: Commms Weekly Call Reminder
on:
  schedule:
    - cron:  '0 15 * * 2'
  workflow_dispatch:
jobs:
  send-updates:
    name: Sends alerts to the comms channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: '3.8'
          architecture: 'x64'
          TIME: 'Tuesday, 6pm CET'
      - name: Install Dependencies
        run: |
          pip install -r actions/requirements.txt
      - name: Send updates
        env:
          IMG: 'Banner_comms.png'
          TITLE: 'Comms Working Group Call'
          TEXT: 'Hi everyone 😁☀️🌈\n☎️ Comms Working Group call in 50min on Working Group VC - Comms channel https:\/\/discord.gg\/s2JuQCBNS4\nAGENDA & CALL NOTES\nhttps:\/\/docs.google.com\/document\/d\/1UTNNyYLf6WC1wlytoU9IJ46z2I32NX0MrtJOs3j9Ahw\/edit\n**MANIFESTO**\nhttps:\/\/docs.google.com\/document\/d\/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI\/edit#\n**MIRO BOARD**\nLink: https:\/\/miro.com\/app\/board\/o9J_kjDw5AE=\/\nPassword: TokenEngineering' 
          KEY: ${{ secrets.ENCRYPTION_KEY }}
          URL: '8ef910a95622fa2e7b9cc64f172e58e1f7dc9f10817caa43cfb322ae61b211df5f9e536463fa1dc23bef9708442240b0eceb2d02c1e33325f5d7a0f28e34ce74d6d6ccc94a06a3f2fea1441b257195e92adcded2639bbb12df97ecb51ada44df560497c349951f3ed2ddc029f32c4df468295783c516ad869c8bee8f829a78e606a3c709f7e69b94792860265bbf7c13b9d73f888b96ce66d618c3e88a225e7b'
        run: |
          python actions/alerts.py
