name: Comms Weekly Call Reminder
on:
  schedule:
    - cron:  '0 15 * * 2'
  workflow_dispatch:
jobs:
  send-updates:
    name: Sends alerts to the comms channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4    
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          pip install -r actions/requirements.txt
      - name: Send updates
        env:
          IMG: 'Banner_comms.png'
          TITLE: 'Comms Working Group Call'
          TEXT: 'Hi everyone 😁☀️🌈\n☎️ Comms Working Group call in 1hour on Working Group VC - Comms channel\n[https://discord.gg/s2JuQCBNS4](https://discord.gg/s2JuQCBNS4)\n**AGENDA & CALL NOTES**\n[https://docs.google.com/document/d/1UTNNyYLf6WC1wlytoU9IJ46z2I32NX0MrtJOs3j9Ahw/edit](https://docs.google.com/document/d/1UTNNyYLf6WC1wlytoU9IJ46z2I32NX0MrtJOs3j9Ahw/edit)\n**MANIFESTO**\n[https://docs.google.com/document/d/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI/edit#](https://docs.google.com/document/d/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI/edit#)\n**MIRO BOARD**\nLink: [https://miro.com/app/board/o9J_kjDw5AE=/](https://miro.com/app/board/o9J_kjDw5AE=/)\nPassword: TokenEngineering' 
          KEY: ${{ secrets.ENCRYPTION_KEY }}
          URL: 'f915a4aefb1ff6ee1eaea3af5b5b2f38b2b7c227395e5b16538feae3785c0ce9909e4e2bc383e11f8a6d82632a471d7bd04287689c9af478d5b96c64c6efee2a091077990f0503c31f02caddc2f74fee43f100da0e16ea81f4402a2dab61ffcc4ea51689a93aaa60a72060c79365ad37d76f6789151b75f4d0f3cb5338cdf072af8cd282d4c3ef343105a8de307d6bb992d19c2dc1b8d070c6a70ba3f7e28dd9'
          TIME: 'Tuesday, 6pm CET'
        run: |
          python actions/alerts.py
