name: 0mega WG bi-weekly sync
on:
  schedule:
    - cron:  '0 17 * * 3'
  workflow_dispatch:
jobs:
  send-updates:
    name: Send alert to the 0mega channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4    
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          pip install -r actions/requirements.txt
      - name: Send updates
        env:
          IMG: 'Banner_omega.png'
          TITLE: '0mega WG bi-weekly sync'
          TEXT: "0mega biweekly sync call in 1hour.\n[Agenda](https://www.google.com/url?q=https://docs.google.com/document/d/1TlkVH8dX1XoiUO57MXMrRzp1-JlQj2sbo4RCEe437PY/edit%23heading%3Dh.mfwf7l9lteyu&sa=D&source=calendar&usd=2&usg=AOvVaw26XsyPDhlLj5ApaCH34n-Z)\nPlease find our [summary from 3.2.2020](https://docs.google.com/document/d/1TlkVH8dX1XoiUO57MXMrRzp1-JlQj2sbo4RCEe437PY/edit#heading=h.za37xb8l6hwn)\n(scroll up for Proposal Goal and Planned Activities --> please feel free to make concrete suggestions)\nI will have shared a 'question collection'  [and add link here - and in discord] doc separately asap, to iterate on.\nThis 3rd exploratory call will focus on:\n(2) 'Ethical Engineering' - and which questions to ask, based on work of Fabian 'An Interface to Moral Philosophy for Token Engineers'\nGoal for the working group, and regular members is to suggest areas of further investigation, and improve quality of question wrt community survey."
          KEY: ${{ secrets.ENCRYPTION_KEY }}
          URL: 'ea9fe5ec9953210d72b4ce1171c8fc143ccc6f643090524eab13060e2c3a696592a7c9e7a9c5c44edd3857d6537bce2d1f35697f7f976f6d204792843e94552ae550cec079d0d8d34f891b2a8234bf9db8465f968ebb52dae6ec048e00d248c6d6181c5bb352057e80169fa18f19e4219deed33dbdadeb49eb03e8b205769aff59d4ed057348c50fdda2104bb135b1451160cf47bcf3d3b3da6bdb7aeb481b5c'
          TIME: 'Wednesday, 8pm CET'
        run: |
          python actions/alerts.py
