name: Orientation - Welcome to the TEC!
on:
  schedule:
    - cron:  '0 16 * * 3'
  workflow_dispatch:
jobs:
  send-updates:
    name: Send AMA alert to general channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          pip install -r actions/requirements.txt
      - name: Send updates
        env:
          IMG: 'banner_orientation.png'
          TITLE: 'Orientation - Welcome to the TEC!'
          TEXT: "Join the Orientation call!\nWe meet at the TEC Community Hall voice channel:\n[https://discord.gg/fNPx3a2h9R](https://discord.gg/fNPx3a2h9R)\nIf you're new to the TEC, join us for an orientation session to learn more about the TEC! Everyone is welcome 🥳"
          KEY: ${{ secrets.ENCRYPTION_KEY }}
          URL: '8ef910a95622fa2e7b9cc64f172e58e1f7dc9f10817caa43cfb322ae61b211df5f9e536463fa1dc23bef9708442240b0eceb2d02c1e33325f5d7a0f28e34ce74d6d6ccc94a06a3f2fea1441b257195e92adcded2639bbb12df97ecb51ada44df560497c349951f3ed2ddc029f32c4df468295783c516ad869c8bee8f829a78e606a3c709f7e69b94792860265bbf7c13b9d73f888b96ce66d618c3e88a225e7b'
          TIME: 'Wednesday, 6pm CET'
        run: |
          python actions/alerts.py
