name: TEC Soft Gov Weekly Sync
on:
  schedule:
    - cron:  '0 16 * * 1'
  workflow_dispatch:
jobs:
  send-updates:
    name: Sends alerts to the SoftGov channel
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2     
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        run: pip install -r actions/requirements.txt

      - name: Send alerts to Discord
        env:
          IMG: './resources/Banner_transparency.png'
          TITLE: 'Soft Gov Weekly Sync'
          TEXT: 'Join the weekly sync call at NEW Discord Soft Gov Voice Channel:\nhttps:\/\/discord.gg\/ZJ7cbpPBhW\n**AGENDA**\nhttps:\/\/docs.google.com\/document\/d\/1R8yLfht6GvGHr8VDvyZ-sVP1s54rPLY4MtXPBOqHtO0\/edit#'
          KEY: ${{ secrets.EncryptionKey }}
          URL: '691f57262d81eedbdc667da455a736fc0f18880fe0538648f21171467f2122d46d34440d5d4df9577aa0850680ad8b756ac67f75cdba8cec4e7f842e5691153bf5f1cf195aa8cd3a093d65b57c5cfe963d6f2b76d09d67060bcdc21baaefef9a3eeb9da7a3bed9937b34c0af5df12b84e9a19629040e0b69fc034b01f2641a455fab3f41004e3bea402b1f51b88e7026dbbdf8c084ad325e7d8c8c30550c88ea'
          TIME: 'Monday, 3pm CET Bi-weekly'
        run: python actions/alerts.py
