name: Transparency WG Sync
on:
  schedule:
    - cron:  '0 12 * * 1'
  workflow_dispatch:
jobs:
  send-updates:
    name: Sends alerts to the transparency channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: actions/setup-python@v3
        name: Set up Python
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          pip install -r actions/requirements.txt
      - name: Send updates
        env:
          IMG: 'Banner_transparency.png'
          TITLE: 'Transparency WG Sync'
          TEXT: '☎️ Transparency WG Call in 1h\n🌟On the Transparency Voice Channel: [https://discord.gg/CRSKAJtFMH](https://discord.gg/CRSKAJtFMH)\n**AGENDA & NOTES**\n[https://docs.google.com/document/d/1jbuqlIXd3s9gRwXbT9ND0zUbE0MaEP9EyO6sHY46iOY/edit](https://docs.google.com/document/d/1jbuqlIXd3s9gRwXbT9ND0zUbE0MaEP9EyO6sHY46iOY/edit)\n**MANIFESTO**\n[https://docs.google.com/document/d/19-YlxdBuivR6qwSTPvlSP6kSLExUDSYT5frp7qaArFI/edit#heading=h.4qr126s3qfr1](https://docs.google.com/document/d/19-YlxdBuivR6qwSTPvlSP6kSLExUDSYT5frp7qaArFI/edit#heading=h.4qr126s3qfr1)\nLook forward to seeing you all there - have a beautiful day! 🌈' 
          KEY: ${{ secrets.ENCRYPTION_KEY }}
          URL: '03f6f819b1e3386eddd0f14ac7f8c83840d96d3c86c440f1c0bb23e210a03f8a892e108f2caf296fa4bcebe4e3a2d74c733ad766c514daab76631addad133d0beb105a0c8caa16af306a20865d01583d2c4a558ecc2de18039a71cbbc33d13fafe40cb6a93ba491392f84c9810e5b4a43ed1ca8d7249ade697968aa54d46af742e30616ec41f2f8b2fcc182cdf2ff5d36b55add0e5a1b70e5907f1d41528d884'
          TIME: 'Monday 3pm CET, Bi-weekly'
        run: |
          python actions/alerts.py
